#!/bin/bash
set -e

DOTFILES="$HOME/.config"

echo "==> Starting bootstrap..."

# ── 1. Install Homebrew ──────────────────────────────
if ! command -v brew &>/dev/null; then
  echo "==> Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # Apple Silicon
  if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
else
  echo "==> Homebrew already installed"
fi

# ── 2. Clone dotfiles ────────────────────────────────
if [[ ! -d "$DOTFILES/.git" ]]; then
  echo "==> Cloning dotfiles..."
  git clone https://github.com/lyleLH/.config.git "$DOTFILES"
else
  echo "==> Dotfiles already cloned at $DOTFILES"
fi

cd "$DOTFILES"

# ── 3. Install brew packages ─────────────────────────
echo "==> Installing brew packages from Brewfile..."
brew bundle --file="$DOTFILES/Brewfile" --no-lock

# ── 4. Symlinks ──────────────────────────────────────
echo "==> Creating symlinks..."

# ~/.zshrc -> dotfiles
ln -sf "$DOTFILES/zsh/.zshrc" "$HOME/.zshrc"

# Goku EDN config (goku reads from env var, set in .zshrc)
# karabiner.json is auto-generated by goku

echo "==> Symlinks done"

# ── 5. Tmux Plugin Manager ──────────────────────────
TPM_DIR="$DOTFILES/tmux/plugins/tpm"
if [[ ! -d "$TPM_DIR/.git" ]]; then
  echo "==> Installing tmux plugin manager (tpm)..."
  git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
else
  echo "==> tpm already installed"
fi

# ── 6. Zinit (auto-installs on first shell, but pre-install for speed) ──
ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
if [[ ! -d "$ZINIT_HOME" ]]; then
  echo "==> Installing zinit..."
  mkdir -p "$(dirname "$ZINIT_HOME")"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
else
  echo "==> zinit already installed"
fi

# ── 7. asdf plugins ─────────────────────────────────
if command -v asdf &>/dev/null; then
  echo "==> Setting up asdf plugins..."
  asdf plugin add ruby 2>/dev/null || true
  asdf plugin add python 2>/dev/null || true
  asdf plugin add nodejs 2>/dev/null || true
  echo "    Run 'asdf install' in project dirs to install specific versions"
else
  echo "==> asdf not found, skipping"
fi

# ── 8. Goku (generate karabiner.json) ───────────────
if command -v goku &>/dev/null; then
  echo "==> Running goku to generate karabiner.json..."
  export GOKU_EDN_CONFIG_FILE="$DOTFILES/goku_config/karabiner.edn"
  goku || echo "    (goku failed — Karabiner may not be installed yet)"
fi

# ── 9. macOS defaults (optional) ─────────────────────
echo "==> Setting macOS defaults..."
# Fast key repeat
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15
# Show hidden files in Finder
defaults write com.apple.finder AppleShowAllFiles -bool true

echo ""
echo "==> Bootstrap complete!"
echo ""
echo "Next steps:"
echo "  1. Open a new terminal — zinit will auto-install zsh plugins"
echo "  2. Run 'p10k configure' if prompt looks wrong"
echo "  3. Open tmux and press prefix+I to install tmux plugins"
echo "  4. Install asdf versions: cd <project> && asdf install"
